<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" http-equiv="refresh" content="0;url=index?user_id=${user.user_id}">
        <title>
            登录成功
        </title>
        <meta name="renderer" content="webkit">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
        <meta name="apple-mobile-web-app-status-bar-style" content="black">
        <meta name="apple-mobile-web-app-capable" content="yes">
        <meta name="format-detection" content="telephone=no">
        <link rel="stylesheet" href="./css/x-admin.css" media="all">
    </head>
    <body>
        <div class="x-body">
            <p> &nbsp;</p>

                <#--<p>
                    <h1 style="text-align:center;font-family:verdana; font-family:arial;color:gray;font-size:20px;">登录成功！欢迎您，${user.user_id}！</h1>
            <button  class="layui-btn" style="margin-left: 700px" onclick="window.location.href='index?user_id=${user.user_id}'">点击确定</button>
                </p>-->
            
            <p> &nbsp;</p>
            <p> &nbsp;</p>
            <p> &nbsp;</p>
            <p>  </p>
            <#--<div align="center">
                <img src="images/back-1.png" />
            </div>-->

            
        </div>
       <#-- <div class="layui-footer footer footer-demo">
            <div class="layui-main">
                
                <p>
                    <a href="/">
                        Copyright ©2021 高金满 v1.0 All Rights Reserved.
                    </a>
                </p>
                
            </div>
        </div>-->
        <script src="./lib/layui/layui.js" charset="utf-8"></script>
        <script src="./js/x-admin.js"></script>
        <script>
        var _hmt = _hmt || [];
        (function() {
          var hm = document.createElement("script");
          hm.src = "https://hm.baidu.com/hm.js?b393d153aeb26b46e9431fabaf0f6190";
          var s = document.getElementsByTagName("script")[0]; 
          s.parentNode.insertBefore(hm, s);
        })();
        </script>
    </body>
</html>